In [3]:
#pip install rasterio

In [1]:
import rasterio
import numpy as np
import pandas as pd

### По всему региону

In [60]:
src = rasterio.open("lcz.tif")

In [65]:
lcz = src.read(1).astype(int)
nodata = src.nodata
mask = (~np.isnan(lcz)) & (lcz != nodata) & (lcz > 0)
lcz = lcz[mask]

In [66]:
values, counts = np.unique(lcz, return_counts=True)

df = pd.DataFrame({
    "LCZ": values,
    "pixels": counts})

df["share (%)"] = df["pixels"] / df["pixels"].sum() * 100

In [67]:
lcz_names = {
1:"Compact High-Rise",
2:"Compact Mid-Rise",
3:"Compact Low-Rise",
4:"Open High-Rise",
5:"Open Mid-Rise",
6:"Open Low-Rise",
7:"Lightweight low-rise",
8:"Large low-rise",
9:"Sparsely built",
10:"Heavy industry",
11:"Dense trees",
12:"Scattered trees",
13:"Bush or scrub",
14:"Low plants",
15:"Bare rock or paved",
16:"Bare soil or sand",
17:"Water"}
df["name"] = df["LCZ"].map(lcz_names)

In [68]:
df = df.sort_values("LCZ")
df

    LCZ  pixels  share (%)                  name
0     1    3864   1.296449     Compact High-Rise
1     2    2461   0.825714      Compact Mid-Rise
2     3    6429   2.157057      Compact Low-Rise
3     4    2155   0.723045        Open High-Rise
4     5   36346  12.194803         Open Mid-Rise
5     6   24754   8.305457         Open Low-Rise
6     7    2842   0.953547  Lightweight low-rise
7     8    6701   2.248318        Large low-rise
8     9   75909  25.468973        Sparsely built
9    10    2297   0.770689        Heavy industry
10   11    2282   0.765656           Dense trees
11   12    8302   2.785485       Scattered trees
12   13  108666  36.459595         Bush or scrub
13   14    8667   2.907950            Low plants
14   15     497   0.166753    Bare rock or paved
15   16    3866   1.297120     Bare soil or sand
16   17    2007   0.673388                 Water

### По урбанизированным территориям

Данные по урабнизированным территориям были взяты с [Global Human Settlement Layer](https://human-settlement.emergency.copernicus.eu/download.php?ds=smod) и обрезаны по области исследования.

Pesaresi, M., Schiavina, M., Politis, P., Freire, S., Krasnodębska, K., Uhl, J. H., … Kemper, T. (2024). Advances on the Global Human Settlement Layer by joint assessment of Earth Observation and population survey data. International Journal of Digital Earth, 17(1).

In [74]:
src_1 = rasterio.open("lcz_urb.tif")

In [75]:
lcz_1 = src_1.read(1).astype(int)
nodata_1 = src_1.nodata
mask_1 = (~np.isnan(lcz_1)) & (lcz_1 != nodata_1) & (lcz_1 > 0)
lcz_1 = lcz_1[mask_1]

In [76]:
values_1, counts_1 = np.unique(lcz_1, return_counts=True)

df_1 = pd.DataFrame({
    "LCZ": values_1,
    "pixels": counts_1})

df_1["share (%)"] = df_1["pixels"] / df_1["pixels"].sum() * 100

In [77]:
df_1["name"] = df_1["LCZ"].map(lcz_names)

In [78]:
df_1 = df_1.sort_values("LCZ")
df_!

    LCZ  pixels  share (%)                  name
0     1    2701   2.924806     Compact High-Rise
1     2    2444   2.646511      Compact Mid-Rise
2     3    5912   6.401871      Compact Low-Rise
3     4    1559   1.688179        Open High-Rise
4     5   26362  28.546368         Open Mid-Rise
5     6    6998   7.577858         Open Low-Rise
6     7    2279   2.467839  Lightweight low-rise
7     8    4627   5.010395        Large low-rise
8     9   14250  15.430762        Sparsely built
9    10    2022   2.189544        Heavy industry
10   11     859   0.930177           Dense trees
11   12    3568   3.863646       Scattered trees
12   13   13754  14.893663         Bush or scrub
13   14    3504   3.794343            Low plants
14   15     444   0.480790    Bare rock or paved
15   16     544   0.589076     Bare soil or sand
16   17     521   0.564170                 Water